import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    docs: [{ type: 'autogenerated', dirName: '.' }], // scan /docs recursively
};

export default sidebars;
