# workflow to build proxy image in the k8shell repository.

name: Build docs image
description: Build docs image and push it to the registry

on:
  push:
    branches:
      - 'main'  
    tags:
      - 'v*'

concurrency:
  # cancel the same workflow if it is running already
  group: docs-image-workflow
  cancel-in-progress: true

jobs:
  docs-image:
    runs-on: k8shell-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Build Python package
        run: |
          # Install dependencies
          python -m pip install --upgrade pip
          pip install sphinx myst_parser sphinx_copybutton furo setuptools_scm sphinxcontrib.mermaid
          rm -fr _build
          make html
          rm -fr docker/docs/files
          mkdir docker/docs/files
          cp -r _build/html/* docker/docs/files

          # Set environment variables
          echo "REPO_NAME=$(cat docker/docs/BUILD)" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(make version)" >> $GITHUB_ENV

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.HARBOR_USER }}
          password: ${{ env.HARBOR_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: "docker/docs"
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}
          push: true
